package net.xgs.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("base_alarm_msg", "id", BaseAlarmMsg.class);
		arp.addMapping("base_android_update", "id", BaseAndroidUpdate.class);
		arp.addMapping("base_block", "id", BaseBlock.class);
		arp.addMapping("base_block_history_data", "id", BaseBlockHistoryData.class);
		arp.addMapping("base_block_machine", "id", BaseBlockMachine.class);
		arp.addMapping("base_machine", "id", BaseMachine.class);
		arp.addMapping("base_machine_limit", "id", BaseMachineLimit.class);
		arp.addMapping("base_machine_machine_type", "id", BaseMachineMachineType.class);
		arp.addMapping("base_machine_params", "id", BaseMachineParams.class);
		arp.addMapping("base_machine_type", "id", BaseMachineType.class);
		arp.addMapping("base_manufactor", "id", BaseManufactor.class);
		arp.addMapping("base_member", "id", BaseMember.class);
		arp.addMapping("base_member_block", "id", BaseMemberBlock.class);
		arp.addMapping("base_org", "id", BaseOrg.class);
		arp.addMapping("base_task_object", "id", BaseTaskObject.class);
		arp.addMapping("base_task_plan", "id", BaseTaskPlan.class);
		arp.addMapping("base_task_plan_job", "id", BaseTaskPlanJob.class);
		arp.addMapping("data_cmd_log", "id", DataCmdLog.class);
		arp.addMapping("data_machine", "id", DataMachine.class);
		arp.addMapping("day_history_data_machine", "id", DayHistoryDataMachine.class);
		arp.addMapping("history_data_machine", "id", HistoryDataMachine.class);
		arp.addMapping("sys_functions", "id", SysFunctions.class);
		arp.addMapping("sys_menu", "id", SysMenu.class);
		arp.addMapping("sys_role", "id", SysRole.class);
	}
}

