package net.xgs.model;

import net.xgs.model.base.BaseBaseMachineParams;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMachineParams extends BaseBaseMachineParams<BaseMachineParams> {
	public static final BaseMachineParams dao = new BaseMachineParams().dao();
}
