package net.xgs.model;

import net.xgs.model.base.BaseBaseMachineRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMachineRelation extends BaseBaseMachineRelation<BaseMachineRelation> {
	public static final BaseMachineRelation dao = new BaseMachineRelation().dao();
}
