package net.xgs.model;

import net.xgs.model.base.BaseBaseTaskPlanJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseTaskPlanJob extends BaseBaseTaskPlanJob<BaseTaskPlanJob> {
	public static final BaseTaskPlanJob dao = new BaseTaskPlanJob().dao();
}
