package net.xgs.model;

import net.xgs.model.base.BaseBaseAlarmMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseAlarmMsg extends BaseBaseAlarmMsg<BaseAlarmMsg> {
	public static final BaseAlarmMsg dao = new BaseAlarmMsg().dao();
}
