package net.xgs.model;

import net.xgs.model.base.BaseBaseTaskPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseTaskPlan extends BaseBaseTaskPlan<BaseTaskPlan> {
	public static final BaseTaskPlan dao = new BaseTaskPlan().dao();
}
