package net.xgs.model;

import net.xgs.model.base.BaseBaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMember extends BaseBaseMember<BaseMember> {
	public static final BaseMember dao = new BaseMember().dao();
}
