package net.xgs.model;

import net.xgs.model.base.BaseBaseOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseOrg extends BaseBaseOrg<BaseOrg> {
	public static final BaseOrg dao = new BaseOrg().dao();
}
