package net.xgs.model;

import net.xgs.model.base.BaseBaseBlockHistoryData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseBlockHistoryData extends BaseBaseBlockHistoryData<BaseBlockHistoryData> {
	public static final BaseBlockHistoryData dao = new BaseBlockHistoryData().dao();
}
