package net.xgs.model;

import net.xgs.model.base.BaseBaseTaskObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseTaskObject extends BaseBaseTaskObject<BaseTaskObject> {
	public static final BaseTaskObject dao = new BaseTaskObject().dao();
}
