package net.xgs.model;

import net.xgs.model.base.BaseBaseMemberBlock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMemberBlock extends BaseBaseMemberBlock<BaseMemberBlock> {
	public static final BaseMemberBlock dao = new BaseMemberBlock().dao();
}
