package net.xgs.model;

import net.xgs.model.base.BaseBaseBlockMachine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseBlockMachine extends BaseBaseBlockMachine<BaseBlockMachine> {
	public static final BaseBlockMachine dao = new BaseBlockMachine().dao();
}
