package net.xgs.model;

import net.xgs.model.base.BaseBaseMachineType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMachineType extends BaseBaseMachineType<BaseMachineType> {
	public static final BaseMachineType dao = new BaseMachineType().dao();
}
