package net.xgs.model;

import net.xgs.model.base.BaseBaseManufactor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseManufactor extends BaseBaseManufactor<BaseManufactor> {
	public static final BaseManufactor dao = new BaseManufactor().dao();
}
