package net.xgs.model;

import net.xgs.model.base.BaseBaseBlock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseBlock extends BaseBaseBlock<BaseBlock> {
	public static final BaseBlock dao = new BaseBlock().dao();
}
