package net.xgs.model;

import net.xgs.model.base.BaseBaseMachineMachineType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMachineMachineType extends BaseBaseMachineMachineType<BaseMachineMachineType> {
	public static final BaseMachineMachineType dao = new BaseMachineMachineType().dao();
}
