package net.xgs.model;

import net.xgs.model.base.BaseBaseMachine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMachine extends BaseBaseMachine<BaseMachine> {
	public static final BaseMachine dao = new BaseMachine().dao();
}
