package net.xgs.model;

import net.xgs.model.base.BaseBaseMachineLimit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMachineLimit extends BaseBaseMachineLimit<BaseMachineLimit> {
	public static final BaseMachineLimit dao = new BaseMachineLimit().dao();
}
