package net.xgs.model;

import net.xgs.model.base.BaseBaseAndroidUpdate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseAndroidUpdate extends BaseBaseAndroidUpdate<BaseAndroidUpdate> {
	public static final BaseAndroidUpdate dao = new BaseAndroidUpdate().dao();
}
