package net.xgs.model;

import net.xgs.model.base.BaseDataCmdLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataCmdLog extends BaseDataCmdLog<DataCmdLog> {
	public static final DataCmdLog dao = new DataCmdLog().dao();
}
