package net.xgs.model;

import net.xgs.model.base.BaseDataMachine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DataMachine extends BaseDataMachine<DataMachine> {
	public static final DataMachine dao = new DataMachine().dao();
}
