package net.xgs.model;

import net.xgs.model.base.BaseDayHistoryDataMachine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DayHistoryDataMachine extends BaseDayHistoryDataMachine<DayHistoryDataMachine> {
	public static final DayHistoryDataMachine dao = new DayHistoryDataMachine().dao();
}
