package net.xgs.model;

import net.xgs.model.base.BaseHistoryDataMachine;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class HistoryDataMachine extends BaseHistoryDataMachine<HistoryDataMachine> {
	public static final HistoryDataMachine dao = new HistoryDataMachine().dao();
}
