package net.xgs.model;

import net.xgs.model.base.BaseSysFunctions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFunctions extends BaseSysFunctions<SysFunctions> {
	public static final SysFunctions dao = new SysFunctions().dao();
}
