package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseTaskObject<M extends BaseBaseTaskObject<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setPlanId(java.lang.String planId) {
		set("plan_id", planId);
	}

	public java.lang.String getPlanId() {
		return get("plan_id");
	}

	public void setMachineId(java.lang.String machineId) {
		set("machine_id", machineId);
	}

	public java.lang.String getMachineId() {
		return get("machine_id");
	}

	public void setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public void setParameterList(java.lang.String parameterList) {
		set("parameter_list", parameterList);
	}

	public java.lang.String getParameterList() {
		return get("parameter_list");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
