package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseMachine<M extends BaseBaseMachine<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTerminalId(java.lang.String terminalId) {
		set("terminal_id", terminalId);
	}

	public java.lang.String getTerminalId() {
		return get("terminal_id");
	}

	public void setParentId(java.lang.String parentId) {
		set("parent_id", parentId);
	}

	public java.lang.String getParentId() {
		return get("parent_id");
	}

	public void setSystemId(java.lang.String systemId) {
		set("system_id", systemId);
	}

	public java.lang.String getSystemId() {
		return get("system_id");
	}

	public void setDeviceId(java.lang.String deviceId) {
		set("device_id", deviceId);
	}

	public java.lang.String getDeviceId() {
		return get("device_id");
	}

	public void setSystemCommand(java.lang.String systemCommand) {
		set("system_command", systemCommand);
	}

	public java.lang.String getSystemCommand() {
		return get("system_command");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setMachineIcon(java.lang.String machineIcon) {
		set("machine_icon", machineIcon);
	}

	public java.lang.String getMachineIcon() {
		return get("machine_icon");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setMachineStatus(java.lang.String machineStatus) {
		set("machine_status", machineStatus);
	}

	public java.lang.String getMachineStatus() {
		return get("machine_status");
	}

	public void setIsControlData(java.lang.String isControlData) {
		set("is_control_data", isControlData);
	}

	public java.lang.String getIsControlData() {
		return get("is_control_data");
	}

	public void setControlDataName(java.lang.String controlDataName) {
		set("control_data_name", controlDataName);
	}

	public java.lang.String getControlDataName() {
		return get("control_data_name");
	}

	public void setControlDataUnit(java.lang.String controlDataUnit) {
		set("control_data_unit", controlDataUnit);
	}

	public java.lang.String getControlDataUnit() {
		return get("control_data_unit");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
