package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDayHistoryDataMachine<M extends BaseDayHistoryDataMachine<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setMachineId(java.lang.String machineId) {
		set("machine_id", machineId);
	}

	public java.lang.String getMachineId() {
		return get("machine_id");
	}

	public void setDataType(java.lang.Integer dataType) {
		set("data_type", dataType);
	}

	public java.lang.Integer getDataType() {
		return get("data_type");
	}

	public void setMaxData(java.lang.String maxData) {
		set("max_data", maxData);
	}

	public java.lang.String getMaxData() {
		return get("max_data");
	}

	public void setMinData(java.lang.String minData) {
		set("min_data", minData);
	}

	public java.lang.String getMinData() {
		return get("min_data");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

}
