package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseMachineMachineType<M extends BaseBaseMachineMachineType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setMachineId(java.lang.String machineId) {
		set("machine_id", machineId);
	}

	public java.lang.String getMachineId() {
		return get("machine_id");
	}

	public void setMachineTypeId(java.lang.String machineTypeId) {
		set("machine_type_id", machineTypeId);
	}

	public java.lang.String getMachineTypeId() {
		return get("machine_type_id");
	}

	public void setManufactorId(java.lang.String manufactorId) {
		set("manufactor_id", manufactorId);
	}

	public java.lang.String getManufactorId() {
		return get("manufactor_id");
	}

}
