package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseTaskPlanJob<M extends BaseBaseTaskPlanJob<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
	}

	public java.lang.String getTaskName() {
		return get("task_name");
	}

	public void setTaskType(java.lang.Integer taskType) {
		set("task_type", taskType);
	}

	public java.lang.Integer getTaskType() {
		return get("task_type");
	}

	public void setBlockId(java.lang.String blockId) {
		set("block_id", blockId);
	}

	public java.lang.String getBlockId() {
		return get("block_id");
	}

	public void setTaskStatus(java.lang.Integer taskStatus) {
		set("task_status", taskStatus);
	}

	public java.lang.Integer getTaskStatus() {
		return get("task_status");
	}

	public void setEndMark(java.lang.Integer endMark) {
		set("end_mark", endMark);
	}

	public java.lang.Integer getEndMark() {
		return get("end_mark");
	}

	public void setMachineId(java.lang.String machineId) {
		set("machine_id", machineId);
	}

	public java.lang.String getMachineId() {
		return get("machine_id");
	}

	public void setStartTime(java.lang.String startTime) {
		set("start_time", startTime);
	}

	public java.lang.String getStartTime() {
		return get("start_time");
	}

	public void setRunTime(java.lang.String runTime) {
		set("run_time", runTime);
	}

	public java.lang.String getRunTime() {
		return get("run_time");
	}

	public void setEndTime(java.lang.String endTime) {
		set("end_time", endTime);
	}

	public java.lang.String getEndTime() {
		return get("end_time");
	}

	public void setDuration(java.lang.Integer duration) {
		set("duration", duration);
	}

	public java.lang.Integer getDuration() {
		return get("duration");
	}

	public void setPeriod(java.lang.Integer period) {
		set("period", period);
	}

	public java.lang.Integer getPeriod() {
		return get("period");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
