package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseMachineLimit<M extends BaseBaseMachineLimit<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setDataType(java.lang.Integer dataType) {
		set("data_type", dataType);
	}

	public java.lang.Integer getDataType() {
		return get("data_type");
	}

	public void setMachineId(java.lang.String machineId) {
		set("machine_id", machineId);
	}

	public java.lang.String getMachineId() {
		return get("machine_id");
	}

	public void setBlockId(java.lang.String blockId) {
		set("block_id", blockId);
	}

	public java.lang.String getBlockId() {
		return get("block_id");
	}

	public void setMachineName(java.lang.String machineName) {
		set("machine_name", machineName);
	}

	public java.lang.String getMachineName() {
		return get("machine_name");
	}

	public void setMaxValue(java.lang.Integer maxValue) {
		set("max_value", maxValue);
	}

	public java.lang.Integer getMaxValue() {
		return get("max_value");
	}

	public void setMinValue(java.lang.Integer minValue) {
		set("min_value", minValue);
	}

	public java.lang.Integer getMinValue() {
		return get("min_value");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
