package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseMachineType<M extends BaseBaseMachineType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setIsMain(java.lang.String isMain) {
		set("is_main", isMain);
	}

	public java.lang.String getIsMain() {
		return get("is_main");
	}

	public void setIsController(java.lang.String isController) {
		set("is_controller", isController);
	}

	public java.lang.String getIsController() {
		return get("is_controller");
	}

	public void setTypeImage(java.lang.String typeImage) {
		set("type_image", typeImage);
	}

	public java.lang.String getTypeImage() {
		return get("type_image");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
