package net.xgs.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseBlockHistoryData<M extends BaseBaseBlockHistoryData<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setBlockId(java.lang.String blockId) {
		set("block_id", blockId);
	}

	public java.lang.String getBlockId() {
		return get("block_id");
	}

	public void setBlockName(java.lang.String blockName) {
		set("block_name", blockName);
	}

	public java.lang.String getBlockName() {
		return get("block_name");
	}

	public void setBlockCrops(java.lang.String blockCrops) {
		set("block_crops", blockCrops);
	}

	public java.lang.String getBlockCrops() {
		return get("block_crops");
	}

	public void setBlockThroughput(java.lang.String blockThroughput) {
		set("block_throughput", blockThroughput);
	}

	public java.lang.String getBlockThroughput() {
		return get("block_throughput");
	}

	public void setBlockGrowthStage(java.lang.String blockGrowthStage) {
		set("block_growth_stage", blockGrowthStage);
	}

	public java.lang.String getBlockGrowthStage() {
		return get("block_growth_stage");
	}

	public void setTechnician(java.lang.String technician) {
		set("technician", technician);
	}

	public java.lang.String getTechnician() {
		return get("technician");
	}

	public void setTechnicianMobile(java.lang.String technicianMobile) {
		set("technician_mobile", technicianMobile);
	}

	public java.lang.String getTechnicianMobile() {
		return get("technician_mobile");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

	public java.lang.String getCreateBy() {
		return get("create_by");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

}
